#!/usr/bin/bash

# use ninja if installed
build_tool=""
if [ -f "/usr/bin/ninja" ]; then
    build_tool="-G Ninja"
fi

# build
cmake -B build $build_tool
cmake --build ./build

# run
build/main/main -o report/out.json $@

cd report/
# python venv
if [ ! -d "venv" ]; then
    python3 -m venv ./venv
    ./venv/bin/pip install -r ./requirements.txt
fi

# report
venv/bin/python3 main.py